### ISSUE TITLE
Color issue on windows

### ISSUE THREAD

**Issue by fredericrous** [trntv/sshed#6]
When I list the hosts with `sshed list`, I get bash colors that powershell does not understand.

```
$ sshed.exe list
[36mtest[0m
```

sshed version: 1.0.3
platform: windows 10
term/shell: powershell 5

**Comment by trntv** [comment]
i'm using https://github.com/mgutz/ansi/ to colorize output, seems like it doesn't support windows.

Maybe https://github.com/fatih/color will be a better alternative, but gopkg.in/AlecAivazis/survey.v1 used for dialogs uses mgutz/ansi internally

**Comment by fredericrous** [comment]
dialogs color (green question mark for example) does work on windows! I only noticed the problem with `sshed list` output
