### ISSUE TITLE
host ip does not work

### ISSUE THREAD

**Issue by fredericrous** [trntv/sshed#7]
__environment__
sshed version: 1.0.3
platform: macos high sierra

__.ssh/config__

```
Host test # -- added by sshed
 HostName 10.11.111.11
 Port 22
 User myuser
 IdentityFile ~/.ssh/mykey
```

__error__

```
$ sshed to test
'ad port '22
 Error: exit status 255
```

**Comment by trntv** [comment]
i believe it is same issue as #5, im using a lot of IPs in my config and it works ok
do you use compiled binary or brew formula?

**Comment by fredericrous** [comment]
oops, wrong copy paste. I just updated. Yes I installed with brew formula. I'm behind a proxy but this should have no relationship with this error

**Comment by trntv** [comment]
https://github.com/kevinburke/ssh_config/issues/13
